TRUNCATE TABLE
  "Account",
  "Category",
  "GlobalSetting",
  "League",
  "PasswordResetToken",
  "Player",
  "PlayerRanking",
  "Season",
  "Session",
  "Sport",
  "Tournament",
  "TournamentCategory",
  "TournamentClub",
  "TournamentGroupPoints",
  "TournamentGroupQualifier",
  "TournamentMatch",
  "TournamentPrize",
  "TournamentRankingPoints",
  "TournamentRegistration",
  "TournamentScheduleDay",
  "TournamentSponsor",
  "User",
  "VerificationToken"
RESTART IDENTITY CASCADE;
